import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "../_components/header/Header";
import { adminHeaderLinks } from "@/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body>
        <Header LINKS={adminHeaderLinks} />
        <div className="flex-1">{children}</div>
      </body>
    </html>
  );
}
